
export const TYPES = {
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_ONE_CART : "REMOVE_ONE_CART",
    REMOVE_ALL_PRODUCT : "REMOVE_ALL_PRODUCT",
    CLEAR_CART : "CLEAR_CART",
    FILL_PRODUCT_LIST : "FILL_PRODUCT_LIST",

}